[package]
name = "pyo3-capsule-user"
version = "0.1.0"
authors = ["fx kirin <fx.kirin@gmail.com>"]
edition = "2018"

[lib]
name = "pyo3_capsule_user"
crate-type = ["cdylib"]

[dependencies]
gdb_breakpoint = "0.1.8"

[dependencies.pyo3]
version = "0.16.4"
features = ["extension-module"]
