[tool.poetry]
name = "pyo3-capsule-api"
version = "0.1.0"
description = "Sweet Python Rust Package"
authors = ["fx kirin <fx.kirin@gmail.com>"]

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
